name: .NET with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Docker
    - name: Set up Docker Compose
      run: |
        docker compose -f WarehouseCase/NewWarehouse/docker-compose.yml up -d

    # Wait for services to be ready
    - name: Wait for services
      run: |
        until docker compose -f WarehouseCase/NewWarehouse/docker-compose.yml ps | grep "healthy"; do
          echo "Waiting for services to be healthy..."
          sleep 5
        done

    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore WarehouseCase/NewWarehouse

    # Build the project
    - name: Build
      run: dotnet build --no-restore WarehouseCase/NewWarehouse

    # Test the project
    - name: Test
      run: dotnet test --no-build --verbosity normal WarehouseCase/Testing

    # Clean up Docker services
    - name: Clean up Docker Compose
      if: always()
      run: |
        docker compose -f WarehouseCase/NewWarehouse/docker-compose.yml down
